/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_marisa_AgentNative */

#ifndef _Included_jp_marisa_AgentNative
#define _Included_jp_marisa_AgentNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_marisa_AgentNative
 * Method:    query
 * Signature: ()Ljp/marisa/QueryNative;
 */
JNIEXPORT jobject JNICALL Java_jp_marisa_AgentNative_query
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_AgentNative
 * Method:    key
 * Signature: ()Ljp/marisa/KeyNative;
 */
JNIEXPORT jobject JNICALL Java_jp_marisa_AgentNative_key
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_AgentNative
 * Method:    set_query
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_AgentNative_set_1query___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     jp_marisa_AgentNative
 * Method:    set_query
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_AgentNative_set_1query__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_marisa_AgentNative
 * Method:    set_query
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_AgentNative_set_1query__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jp_marisa_AgentNative
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_marisa_AgentNative_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
