/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_marisa_KeyNative */

#ifndef _Included_jp_marisa_KeyNative
#define _Included_jp_marisa_KeyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_marisa_KeyNative
 * Method:    id
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_KeyNative_id
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_KeyNative
 * Method:    text
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jp_marisa_KeyNative_text__
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_KeyNative
 * Method:    text
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_KeyNative_text__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_marisa_KeyNative
 * Method:    textLength
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_KeyNative_textLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
