/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_marisa_KeysetNative */

#ifndef _Included_jp_marisa_KeysetNative
#define _Included_jp_marisa_KeysetNative
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_marisa_KeysetNative_DEFAULT_WAIT
#define jp_marisa_KeysetNative_DEFAULT_WAIT 1.0f
/*
 * Class:     jp_marisa_KeysetNative
 * Method:    push_back
 * Signature: (Ljp/marisa/KeyNative;)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_KeysetNative_push_1back__Ljp_marisa_KeyNative_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    push_back
 * Signature: (Ljp/marisa/KeyNative;B)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_KeysetNative_push_1back__Ljp_marisa_KeyNative_2B
  (JNIEnv *, jobject, jobject, jbyte);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    push_back
 * Signature: ([BIIF)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_KeysetNative_push_1back___3BIIF
  (JNIEnv *, jobject, jbyteArray, jint, jint, jfloat);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    get
 * Signature: (I)Ljp/marisa/KeyNative;
 */
JNIEXPORT jobject JNICALL Java_jp_marisa_KeysetNative_get
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    num_keys
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_KeysetNative_num_1keys
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    empty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_marisa_KeysetNative_empty
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_KeysetNative_size
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    total_length
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_KeysetNative_total_1length
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_marisa_KeysetNative_reset
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_marisa_KeysetNative_clear
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    swap
 * Signature: (Ljp/marisa/KeysetNative;)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_KeysetNative_swap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_marisa_KeysetNative
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_marisa_KeysetNative_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
