/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_marisa_QueryNative */

#ifndef _Included_jp_marisa_QueryNative
#define _Included_jp_marisa_QueryNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_marisa_QueryNative
 * Method:    id
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_QueryNative_id
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_QueryNative
 * Method:    text
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jp_marisa_QueryNative_text__
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_QueryNative
 * Method:    text
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_QueryNative_text__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_marisa_QueryNative
 * Method:    textLength
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_QueryNative_textLength
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
