/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_marisa_TrieNative */

#ifndef _Included_jp_marisa_TrieNative
#define _Included_jp_marisa_TrieNative
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_marisa_TrieNative_MARISA_MIN_NUM_TRIES
#define jp_marisa_TrieNative_MARISA_MIN_NUM_TRIES 1L
#undef jp_marisa_TrieNative_MARISA_MAX_NUM_TRIES
#define jp_marisa_TrieNative_MARISA_MAX_NUM_TRIES 127L
#undef jp_marisa_TrieNative_MARISA_DEFAULT_NUM_TRIES
#define jp_marisa_TrieNative_MARISA_DEFAULT_NUM_TRIES 3L
#undef jp_marisa_TrieNative_MARISA_HUGE_CACHE
#define jp_marisa_TrieNative_MARISA_HUGE_CACHE 128L
#undef jp_marisa_TrieNative_MARISA_LARGE_CACHE
#define jp_marisa_TrieNative_MARISA_LARGE_CACHE 256L
#undef jp_marisa_TrieNative_MARISA_NORMAL_CACHE
#define jp_marisa_TrieNative_MARISA_NORMAL_CACHE 512L
#undef jp_marisa_TrieNative_MARISA_SMALL_CACHE
#define jp_marisa_TrieNative_MARISA_SMALL_CACHE 1024L
#undef jp_marisa_TrieNative_MARISA_TINY_CACHE
#define jp_marisa_TrieNative_MARISA_TINY_CACHE 2048L
#undef jp_marisa_TrieNative_MARISA_DEFAULT_CACHE
#define jp_marisa_TrieNative_MARISA_DEFAULT_CACHE 512L
#undef jp_marisa_TrieNative_MARISA_TEXT_TAIL
#define jp_marisa_TrieNative_MARISA_TEXT_TAIL 4096L
#undef jp_marisa_TrieNative_MARISA_BINARY_TAIL
#define jp_marisa_TrieNative_MARISA_BINARY_TAIL 8192L
#undef jp_marisa_TrieNative_MARISA_DEFAULT_TAIL
#define jp_marisa_TrieNative_MARISA_DEFAULT_TAIL 4096L
#undef jp_marisa_TrieNative_MARISA_LABEL_ORDER
#define jp_marisa_TrieNative_MARISA_LABEL_ORDER 65536L
#undef jp_marisa_TrieNative_MARISA_WEIGHT_ORDER
#define jp_marisa_TrieNative_MARISA_WEIGHT_ORDER 131072L
#undef jp_marisa_TrieNative_MARISA_DEFAULT_ORDER
#define jp_marisa_TrieNative_MARISA_DEFAULT_ORDER 131072L
#undef jp_marisa_TrieNative_MARISA_NUM_TRIES_MASK
#define jp_marisa_TrieNative_MARISA_NUM_TRIES_MASK 127L
#undef jp_marisa_TrieNative_MARISA_CACHE_LEVEL_MASK
#define jp_marisa_TrieNative_MARISA_CACHE_LEVEL_MASK 3968L
#undef jp_marisa_TrieNative_MARISA_TAIL_MODE_MASK
#define jp_marisa_TrieNative_MARISA_TAIL_MODE_MASK 61440L
#undef jp_marisa_TrieNative_MARISA_NODE_ORDER_MASK
#define jp_marisa_TrieNative_MARISA_NODE_ORDER_MASK 983040L
#undef jp_marisa_TrieNative_MARISA_CONFIG_MASK
#define jp_marisa_TrieNative_MARISA_CONFIG_MASK 1048575L
/*
 * Class:     jp_marisa_TrieNative
 * Method:    build
 * Signature: (Ljp/marisa/KeysetNative;I)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_build
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    mmap
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_mmap
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    map
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_map
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    load
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_load
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    read
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    save
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_save
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    write
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_write
  (JNIEnv *, jobject, jint);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    lookup
 * Signature: (Ljp/marisa/AgentNative;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_marisa_TrieNative_lookup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    revese_lookup
 * Signature: (Ljp/marisa/AgentNative;)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_reverse_1lookup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    common_prefix_search
 * Signature: (Ljp/marisa/AgentNative;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_marisa_TrieNative_common_1prefix_1search
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    predictive_search
 * Signature: (Ljp/marisa/AgentNative;)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_marisa_TrieNative_predictive_1search
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    num_tries
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_TrieNative_num_1tries
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    num_keys
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_TrieNative_num_1keys
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    num_nodes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_TrieNative_num_1nodes
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    tail_mode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_marisa_TrieNative_tail_1mode
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    node_order
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_marisa_TrieNative_node_1order
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    empty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jp_marisa_TrieNative_empty
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_TrieNative_size
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    io_size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_marisa_TrieNative_io_1size
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_clear
  (JNIEnv *, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    swap
 * Signature: (Ljp/marisa/TrieNative;)V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_swap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jp_marisa_TrieNative
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_marisa_TrieNative_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
